image: alpine

before_script:
    - apk update
    - apk add java

build-job:
  stage: build
  script:
    - make

rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
